---
booktitle: Proceedings of the Thirty-Ninth Conference on Uncertainty in Artificial
  Intelligence
conference_number: '39'
end: 2023-08-04
published: 2023-07-02
shortname: UAI
start: 2023-07-31
volume: '216'
year: '2023'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: UAI-2023
month: 0
cycles: false
bibtex_editor: Evans, Robin J. and Shpitser, Ilya
editor:
- given: Robin J.
  family: Evans
- given: Ilya
  family: Shpitser
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Thirty-Ninth Conference on Uncertainty in Artificial Intelligence
    Held in Pittsburgh, PA, USA on 31 July to 04 August 2023

  Published as Volume 216 by the Proceedings of Machine Learning Research on 02 July 2023.

  Volume Edited by:
    Robin J. Evans
    Ilya Shpitser

  Series Editors:
    Neil D. Lawrence
date_str: 31 Jul--04 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v216"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v216
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v216
email: ''
conference:
  name: Uncertainty in Artificial Intelligence
  url: https://www.auai.org/uai2023/
  location: Pittsburgh, PA, USA
  dates:
  - 2023-07-31
  - 2023-08-01
  - 2023-08-02
  - 2023-08-03
  - 2023-08-04
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v216/UAI2023.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v216/UAI2023.bib
